# The name of the pipeline shown in GitHub Actions
name: Selenium CI Pipeline

# This section defines when the pipeline should run
on:
  # Run this pipeline whenever code is pushed
  push:
    # Only run if the push happens on the main branch
    branches: [ "main" ]

# A pipeline is made up of jobs
jobs:
  # This is the name of the job
  build:
    # The job will run on a GitHub-hosted Ubuntu machine
    runs-on: ubuntu-latest

    # Steps are the actions performed one after another
    steps:
      # Step 1: Download the repository code into the runner machine
      - name: Checkout Code
        uses: actions/checkout@v5

      # Step 2: Install Java so the project can compile and run
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          # Temurin is the Java distribution being used
          distribution: 'temurin'
          # Install Java version 21
          java-version: '21'

      # Step 3: Build the project and run the tests using Maven.
      - name: Build and Run Tests
        run: mvn clean test -Dheadless=true

      # Step 4: Upload the Extent Report so it can be downloaded from GitHub Actions
      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact as it will appear in GitHub Actions.
          name: extent-report
          # Path to the generated report file inside the project
          path: Reports/InventoryAutomationReport.html

      # Step 5: Send the report by email
      - name: Send Email with Extent Report
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP server used to send the email
          server_address: smtp.gmail.com
          # SMTP port for secure TLS email sending
          server_port: 587
          # Email username stored securely in GitHub secrets
          username: ${{ secrets.EMAIL_USERNAME }}
          # Email password or app password stored securely in GitHub secrets
          password: ${{ secrets.EMAIL_PASSWORD }}
          # Subject line of the email
          subject: Automation Test Results - Extent Report for 2nd Group
          # Recipient email address
          to: nqobilemgobozi@gmail.com
          # Sender email address
          from: ${{ secrets.EMAIL_USERNAME }}
          # Message body in the email
          body: Hi,
              I hope you are well.
              please find attached the latest Extent Report.
            
              Kind Regards
              Nqobile CEO

          # Attach the generated report file to the email
          attachments: Reports/InventoryAutomationReport.html